# Copyright 2020 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

timeout: 21600s

steps:
- name: "gcr.io/cloud-foundation-cicd/cft/developer-tools@sha256:a09ad46f513847d31e2cfe20f818c2d64809e7d12695e2e6098900296f6527bf"
  entrypoint: terraform
  args: ["version"]

- name: "gcr.io/cloud-foundation-cicd/cft/developer-tools@sha256:a09ad46f513847d31e2cfe20f818c2d64809e7d12695e2e6098900296f6527bf"
  entrypoint: terragrunt
  args: ["init"]
  dir: "${_TERRAFORM_ROOT}/org"

# Generate a plan for each deployment.
# Non-Terragrunt flags are passed to the underlying calls to terraform, so
# this will generate a separate plan.tfplan file for each deployment.
- name: "gcr.io/cloud-foundation-cicd/cft/developer-tools@sha256:a09ad46f513847d31e2cfe20f818c2d64809e7d12695e2e6098900296f6527bf"
  entrypoint: terragrunt
  args: ["plan-all", "--terragrunt-non-interactive", "-out=plan.tfplan"]
  dir: "${_TERRAFORM_ROOT}/org"

# Check for delete operations.
- name: "gcr.io/cloud-foundation-cicd/cft/developer-tools@sha256:a09ad46f513847d31e2cfe20f818c2d64809e7d12695e2e6098900296f6527bf"
  entrypoint: '${_TERRAFORM_ROOT}/cicd/configs/tf-deletecheck.sh'
  dir: "${_TERRAFORM_ROOT}/org"
  args: ['${_FAIL_ON_DELETES}']

substitutions:
  _TERRAFORM_ROOT: "."
  _FAIL_ON_DELETES: "false"
